### ISSUE TITLE
Not generating nested elements

### ISSUE THREAD

**Issue by scarrick68** [donpark/html2jade#105]
It is generating the ids and classes of the nested elements indented and on new lines, but excluding the elements themselves. Here is a snippet of original HTML and the corresponding Jade that was generated:
```
<div ng-controller="playerCtrl">
    <div id="playerTop" class="player-top">
        <div class="paid-tv"  ng-if="user.type != 'free'">
            <div class="main-player position-div">
                <div id="tv-player"></div>
            </div>
        </div>
```
```
div(ng-controller='playerCtrl')
  #playerTop.player-top
    .paid-tv(ng-if="user.type != 'free'")
      .main-player.position-div
        #tv-player
    | 
```

I wasn't sure if this is a jade shorthand for nesting the same type of element. I didn't see it in their docs, but correct me if I'm wrong.

It compiles back to HTML with reconstituted divs. Is there a way to explicitly have the nested divs preserved when I do HTML to Jade?

**Comment by donpark** [comment]
That is how Jade works which is modeled after CSS selector syntax.
I'm surprised Jade documentation doesn't say this explicitly.

**Comment by donpark** [comment]
re your 'excluding the elements themselves' comment, `div` elements are omitted if an ID or CSS style is defined. html2jade just prefers to omit but jade will also allows `div.paid-tv`.
