### ISSUE TITLE
what's wrong with this ? May be some bugs ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [donpark/html2jade#114]
[http://learnjade.com/tour/nesting/](http://learnjade.com/tour/nesting/)  
**OK**  
![jade-nest-comment-ok](https://cloud.githubusercontent.com/assets/18028768/19051219/b9b4b6fc-89e4-11e6-8261-52e430f8d7dd.PNG)  

[http://html2jade.org/](http://html2jade.org/)  
**Error:**  
![jade-nest-comment-error](https://cloud.githubusercontent.com/assets/18028768/19051241/d63c85c0-89e4-11e6-9262-2e3da65e63a3.PNG)

**Comment by xgqfrms-GitHub** [comment]
@donpark

**Comment by donpark** [comment]
yup. looks like a bug.

**Comment by xgqfrms-GitHub** [comment]
**thanks for your time!**
