### ISSUE TITLE
Null Class value (class="") messes up the translation

### ISSUE THREAD

**Issue by soumendra** [donpark/html2jade#33]
Resulting in jade code like
tr.
or
tr#even.
which get rendered incorrectly (differently from what was intended by and rendered from the html) at least in node.js using express and jade.

**Comment by bit-seq** [comment]
> Fix was to ignore empty class attributes.

Which leads to problems on my specific case, where empty attributes won't be set to some default but should remain empty. Since these are ignored from `html2jade`, these are set default.

**Comment by donpark** [comment]
sorry about that.
a selfish-suggestion: just filter `class=""` out using sed or awk.

**Comment by bit-seq** [comment]
Never mind, I troubleshot this by temporarily set some placeholder class-name.
However, I suggest supporting empty attribute-values
