### ISSUE TITLE
Current version adds unnecessary empty | lines

### ISSUE THREAD

**Issue by DomiR** [donpark/html2jade#93]
The newest version is adding unnecessary empty lines everywhere. I don't think this is supposed to do so and was introduced by the new version.

From the online tool: http://html2jade.aaron-powell.com/ using 0.8.1
```html
<div class="two fields">
    <div class="field">
      <label>First Name</label>
      <input placeholder="First Name" type="text">
    </div>
 </div>
```

```jade
.two.fields
    .field
        label First Name
        |         <- This should not be here!!!
        input(placeholder='First Name', type='text')
```

Kind regards

**Comment by pmeissner** [comment]
After it's done processing, could it loop through the resulting code looking for lines that contain a single pipe character only and eliminate those lines?

**Comment by donpark** [comment]
I think that will remove some intentionally added white-spaces. White-spaces can be ignored, compressed to a single space, or must be left as is. DTD helps differentiate but doesn't cover ugly corner cases.

**Comment by Nedomas** [comment]
This is a huge issue, because a lot of editors have auto trailing space trimming. 

I already get tons of errors like these:
```jade
Message:
    /Users/domas/Developer/test-app1/index.jade:4
    2|   head
    3|     title Beautiful Jade
  > 4|     |
    5|     link(rel='stylesheet', href='vendor/css/bootstrap.min.css')
    6|     |
    7|     link(rel='stylesheet', href='css/app.css')

unexpected text |
```

**Comment by donpark** [comment]
When I have time (warning: not for a while), I'll revisit this issue. One possible compromise is to add an optional flag that filters out white-space only piped lines.

**Comment by blunckr** [comment]
If anyone is looking for a quick fix for this, I just did a find/replace in sublime text with this regex:
`/^\s+\|\s+$\n/`

It removes any line that only has a pipe character. Of course It might remove lines that you actually want, you'll have to just find those manually.

**Comment by ndastur** [comment]
This a major issue, I think. My suggestion would be to roll back the commit until time becomes available to look into a solution. +1 for agrees ;)

**Comment by donpark** [comment]
OK. bumped to major status.

When I find some free time, I'll add a compiler flag to wipe out all 'lone pipe' lines.

Pull request could quicken the process however.
