### ISSUE TITLE
omit commas between attributes

### ISSUE THREAD

**Issue by focusaurus** [donpark/html2jade#96]
Modern jade does not require commas to separate attributes within an HTML element. This makes jade more like HTML and easier to deal with. Could html2jade omit the commas?

**Comment by donpark** [comment]
It'll have to be added as a new feature. I'm rather squeezed just now so you're welcome to submit a PR.

**Comment by donpark** [comment]
This feature is now implemented in version 0.8.3+ via `--noattrcomma` flag 2cc64f2a5a09c3c9eae070e2a4b159355573673b.

**Comment by focusaurus** [comment]
Awesome! Thanks so much. :cake:
